### ISSUE TITLE
test coverage 

### ISSUE THREAD

**Issue by annmedvid** [VovaTereschenko/github-task#1]
Hi @VovaTereschenko. Thank you for completing this technical task. I would ask you to cover it with tests in the amount you feel required for such application.

**Comment by VovaTer** [comment]
Hi @annmedvid! Sure, I'll add some tests at my discretion.

**Comment by VovaTereschenko** [comment]
Sure, @annmedvid - I'll add some tests at my discretion.

**Comment by VovaTer** [comment]
Hey, @annmedvid! I've added some tests without abstracting them and their mocks too much for simplicity reasons.
You can find 
- testing of _api/business logic_:
https://github.com/VovaTereschenko/github-task/blob/master/client/src/views/GithubWidget/GuthubWidget.test.js
- testing some important information to be reflected on UI: https://github.com/VovaTereschenko/github-task/blob/master/client/src/renderers/Repositories/Repositories.test.js
- testing of UI component which has some specifics in its logic:
https://github.com/VovaTereschenko/github-task/blob/master/client/src/components/DebouncedTextField/DebouncedTextField.test.js

<img width="491" alt="Screenshot 2022-11-20 at 18 10 37" src="https://user-images.githubusercontent.com/53568482/202909927-70a577fe-772e-4ea0-a6c1-b8c135a23385.png">

Ping me if anything comes up .)

**Comment by VovaTereschenko** [comment]
Hey, @annmedvid! I've added some tests without abstracting them and their mocks too much for simplicity reasons.

**You can find:**

_api/business logic_ testing:
https://github.com/VovaTereschenko/github-task/blob/master/client/src/views/GithubWidget/GuthubWidget.test.js

testing some important information to be reflected on UI: https://github.com/VovaTereschenko/github-task/blob/master/client/src/renderers/Repositories/Repositories.test.js

testing UI component which has some specifics in its logic:
https://github.com/VovaTereschenko/github-task/blob/master/client/src/components/DebouncedTextField/DebouncedTextField.test.js

<img width="491" alt="Screenshot 2022-11-20 at 18 10 37" src="https://user-images.githubusercontent.com/53568482/202909927-70a577fe-772e-4ea0-a6c1-b8c135a23385.png">

Ping me if anything comes up .)

**Comment by annmedvid** [comment]
Thank you @VovaTereschenko
